{% set name = "vsts" %}
{% set version = "0.1.25" %}

package:
  name: vsts-python-api
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da179160121f5b38be061dbff29cd2b60d5d029b2207102454d77a7114e64f97

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - msrest >=0.6.0,<0.7.0
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - vsts
    - vsts.vss_connection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Microsoft/vsts-python-api
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python wrapper around the VSTS APIs
  doc_url: https://docs.microsoft.com/en-us/rest/api/vsts/
  dev_url: https://github.com/Microsoft/vsts-python-api

extra:
  recipe-maintainers:
    - mariusvniekerk
