{% set name = "vsts" %}
{% set version = "0.1.18" %}

package:
  name: vsts-python-api
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70acf8b373aea77bc219159a9528d8d974c9a6b81ea295d9c5d2baf9a38a1e4e

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - msrest >=0.5.0,<0.6.0
    - python
    - setuptools

test:
  imports:
    - vsts
    - vsts.vss_connection

about:
  home: https://github.com/Microsoft/vsts-python-api
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python wrapper around the VSTS APIs
  doc_url: https://docs.microsoft.com/en-us/rest/api/vsts/
  dev_url: https://github.com/Microsoft/vsts-python-api

extra:
  recipe-maintainers:
    - mariusvniekerk
