{% set name = "vsts" %}
{% set version = "0.1.24" %}

package:
  name: vsts-python-api
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 535ab03148d3c1103a4e1b67fd87948321ff240f8cdf97b5c2684bac0ec6a014

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - msrest >=0.5.0
    - python
    - setuptools

test:
  imports:
    - vsts
    - vsts.vss_connection

about:
  home: https://github.com/Microsoft/vsts-python-api
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python wrapper around the VSTS APIs
  doc_url: https://docs.microsoft.com/en-us/rest/api/vsts/
  dev_url: https://github.com/Microsoft/vsts-python-api

extra:
  recipe-maintainers:
    - mariusvniekerk
